Repository prography/10th_4team_LightOn_BE, pull requests merged in 2025-08, with the labels that each got.

#124 [Feature] 마이페이지 조회 API에 이름 필드 추가
  src/main/java/com/prography/lighton/member/users/application/UserMemberQueryService.java
  src/main/java/com/prography/lighton/member/users/presentation/UserMemberController.java
  src/main/java/com/prography/lighton/member/users/presentation/dto/response/GetMemberInfoResponse.java
  src/main/java/com/prography/lighton/performance/users/application/service/UserPerformanceService.java
  src/main/java/com/prography/lighton/performance/users/presentation/dto/response/GetMyPerformanceStatsResponseDTO.java
Labels: 🔧 feature

#135 [Bug] 선호 장르가 없을 때 추천 공연 조회 불가 문제 해결
  src/main/java/com/prography/lighton/performance/users/application/service/UserRecommendationService.java
Labels: 🐞 bug

#137 [Refactor] 공지사항 리팩토링 및 테스트 코드 작성
  src/main/java/com/prography/lighton/announcement/admin/application/ManageAnnouncementService.java
  src/main/java/com/prography/lighton/announcement/admin/application/ManageAnnouncementUseCase.java
  src/main/java/com/prography/lighton/announcement/admin/presentation/AdminAnnouncementController.java
  src/main/java/com/prography/lighton/announcement/common/domain/entity/Announcement.java
  src/main/java/com/prography/lighton/announcement/users/application/GetAnnouncementService.java
  src/main/java/com/prography/lighton/announcement/users/application/GetAnnouncementUseCase.java
  src/main/java/com/prography/lighton/announcement/users/presentation/UserAnnouncementController.java
  src/test/java/com/prography/lighton/announcement/admin/application/ManageAnnouncementServiceTest.java
  src/test/java/com/prography/lighton/announcement/common/domain/entity/AnnouncementTest.java
  src/test/java/com/prography/lighton/announcement/users/application/GetAnnouncementServiceTest.java
  src/test/java/com/prography/lighton/common/fixture/AnnouncementTestFixture.java
Labels: 🛠 refactor

#148 [Feature] 승인되지 않은 공연도 수정 및 취소 가능하도록 로직 변경
  src/main/java/com/prography/lighton/performance/users/application/service/ArtistPerformanceService.java
  src/main/java/com/prography/lighton/performance/users/application/service/BuskingService.java
Labels: 🔧 feature
